#!/bin/bash

set -x

LLVMDIR=~/llvm-build/llvm/bin
DSTDIR=~/llvm-project/llvm/test/CodeGen

SRCFILENAME=CodeGen/expand-variadic-call.c

clang_regen.sh $SRCFILENAME

SRCFILE=~/llvm-project/clang/test/$SRCFILENAME

CLANG=$LLVMDIR/clang

# disable control presently missing
# -mllvm -expand-variadics-disable=true

GENERIC="-std=c23 $SRCFILE -O1 -emit-llvm -S -ffreestanding -nogpulib -mllvm --expand-variadics-override=disable"

OUTSUBDIR=''
TRIPLE=''
TESTSUFFIX=''
TESTNAME=expand-variadic-call


func () {


OUTFILE=$OUTSUBDIR/$TESTNAME$TESTSUFFIX.ll
OUTFILEDIR=$DSTDIR/$OUTFILE


$CLANG $GENERIC --target=$TRIPLE -S -o $OUTFILEDIR

# Replace any attributes with mustprogress, the forceattrs pass doesn't remove all of them for some reason
sed -i 's_attributes \#\([[:alnum:]]\) = {.*}_attributes \#\1 = { mustprogress }_g' $OUTFILEDIR


$LLVMDIR/opt -S --passes=forceattrs \
             --force-remove-attribute=mustprogress \
             --force-remove-attribute="nobuiltin" \
              $OUTFILEDIR -o $OUTFILEDIR.tmp
mv $OUTFILEDIR.tmp $OUTFILEDIR

$LLVMDIR/opt -S --passes=forceattrs \
             --force-remove-attribute=mustprogress \
             $OUTFILEDIR -o $OUTFILEDIR.tmp
mv $OUTFILEDIR.tmp $OUTFILEDIR


mv $OUTFILEDIR $OUTFILEDIR.tmp
echo '; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: -p --function-signature' > $OUTFILEDIR
echo '; RUN: opt -S --passes=expand-variadics --expand-variadics-override=lowering < %s | FileCheck %s' >> $OUTFILEDIR


cat $OUTFILEDIR.tmp | egrep -v 'source_filename' | egrep -v '; ModuleID|llvm.ident' | egrep -v 'clang version' | egrep -v 'oclc_ABI_version' | egrep -v '; Function Attrs:'  >> $OUTFILEDIR
rm $OUTFILEDIR.tmp



$LLVMDIR/opt -S --passes=expand-variadics --expand-variadics-override=lowering < $OUTFILEDIR | grep '= type' | egrep -v '%struct.__va_list_tag = type|%struct.libcS' > $OUTFILEDIR.types

sed -i 's/^/; CHECK: /g' $OUTFILEDIR.types
(echo '' ; echo "; Check the variables are lowered to the locations this target expects"; echo ''; echo "; The types show the call frames"; cat $OUTFILEDIR.types) > $OUTFILEDIR.tmp.types
mv $OUTFILEDIR.tmp.types $OUTFILEDIR.types

sed -i '/target triple = \(.*\)/{
  s/target/target/g  
  r '$OUTFILEDIR.types'
}' $OUTFILEDIR

rm $OUTFILEDIR.types

sed -i 's/ dso_local / /g' $OUTFILEDIR
sed -i 's/ local_unnamed_addr / /g' $OUTFILEDIR
sed -i 's/ local_unnamed_addr//g' $OUTFILEDIR


llvm_regen.sh CodeGen/$OUTFILE
}



OUTSUBDIR=X86
TRIPLE=i386-unknown-linux-gnu
TESTSUFFIX='-i386-linux'
func

OUTSUBDIR=X86
TRIPLE=x86_64-linux-gnu
TESTSUFFIX='-x64-linux'
func

OUTSUBDIR=X86
TRIPLE=i386-apple-darwin
TESTSUFFIX='-i386-darwin'
func

OUTSUBDIR=X86
TRIPLE=x86_64-apple-darwin
TESTSUFFIX='-x64-darwin'
func


# i386 vs 686?
OUTSUBDIR=X86
TRIPLE=i686-windows-msvc
TESTSUFFIX='-i686-msvc'
func

# OUTSUBDIR=X86
# TRIPLE=x86_64-unknown-windows-msvc
# TESTSUFFIX='-x64-msvc'
# func


OUTSUBDIR=AMDGPU
TRIPLE=amdgcn-amd-amdhsa
TESTSUFFIX=''
func

OUTSUBDIR=NVPTX
TRIPLE=nvptx64-nvidia-cuda
TESTSUFFIX=''
func
